version: '2'

services:
  orders:
    image: 333107818315.dkr.ecr.ap-northeast-2.amazonaws.com/super-order:orders
    build:
      context: .
      dockerfile: ./apps/orders/Dockerfile
    command: npm run start:dev orders
    # env_file:
    #   - ./libs/libs.env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '3000:3000'

  billing:
    image: 333107818315.dkr.ecr.ap-northeast-2.amazonaws.com/super-order:billing
    build:
      context: .
      dockerfile: ./apps/billing/Dockerfile
    command: npm run start:dev billing
    # env_file:
    #   - ./libs/libs.env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
