version: '2'

services:
  orders:
    image: ${{secrets.AWS_ECR_URL}}:orders
    build:
      context: .
      dockerfile: ./apps/orders/Dockerfile
    command: npm run start:dev orders
    # env_file:
    #   - ./libs/libs.env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '3000:3000'

  billing:
    image: ${{secrets.AWS_ECR_URL}}:billing
    build:
      context: .
      dockerfile: ./apps/billing/Dockerfile
    command: npm run start:dev billing
    # env_file:
    #   - ./libs/libs.env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
