version: '2'

services:
  orders:
    image: 895940361152.dkr.ecr.ap-northeast-2.amazonaws.com/orderproject:orders
    build:
      context: .
      dockerfile: ./apps/orders/Dockerfile
    command: npm run start:dev orders
    # env_file:
    #   - ./libs/libs.env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '3000:3000' 

  billing:
    image: 895940361152.dkr.ecr.ap-northeast-2.amazonaws.com/orderproject:billing
    build:
      context: .
      dockerfile: ./apps/billing/Dockerfile
    command: npm run start:dev billing
    # env_file:
    #   - ./libs/libs.env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  auth:
    image: 895940361152.dkr.ecr.ap-northeast-2.amazonaws.com/orderproject:auth
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
    command: npm run start:dev auth
    # env_file:
    #   - ./libs/libs.env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '3001:3001'            

  rabbitmq:
    image: rabbitmq
    ports:
    - '5672:5672'     