name: build-pipeline
on:
  push:
    branches:
      - master
jobs:
  build-image:
    name: Build Image
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        run: |
          docker-compose -f docker-compose.aws.yml build
          docker push ${{secrets.AWS_ECR_REGISTER}}/${{secrets.AWS_ECR_REGISTER}}:orders
          docker push ${{secrets.AWS_ECR_REGISTER}}/${{secrets.AWS_ECR_REGISTER}}:billing
